"""Add Plan and Note models for per-thread planning and notes

Revision ID: 641fc064c0c0
Revises: 73ff85646b19
Create Date: 2025-11-09 19:16:37.498975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641fc064c0c0'
down_revision: Union[str, Sequence[str], None] = '73ff85646b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
